name: push-tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2

      - run: make install

      - run: make lint